### PR TITLE
Add support for sound null-safety

### PR DESCRIPTION
**Pull request by norarrsgd**
This is for #9

### CODE REVIEW

**Comment by norarrsgd** [comment]
@java-james would be great if you push this update to the plugin :D

**Comment by java-james** [comment]
Thanks for this PR.
I will review and get this merged asap

**Comment by norarrsgd** [comment]
Please and thanks @java-james

**Comment by norarrsgd** [comment]
Oh LOL you merged your own changes

**Comment by java-james** [comment]
Yeah sorry Merged PR #11 from long1eu instead of this one for the null safety fix. Didn't notice it was a duplicate PR opened until merged :)

**Pull request closed without merging**
