### PR TITLE
fix opacity issue on ios--using(using color box)

### PR DESCRIPTION
**Pull request by venbrinoDev**
Fix issue on ios 

opacity having issue on ios and it cause janky issue 

i fixed by using color box

### CODE REVIEW

**Review by Adminixtrator — APPROVED** [review]

**Review by Adminixtrator — APPROVED** [review]

**Review by emmanueljoshua1 — APPROVED** [review]

**Comment by emmanueljoshua1** [comment]
Guys please merge this PR.

**Comment by Adminixtrator** [comment]
hey @venbrinoDev @emmanueljoshua1,

you can just switch to `LoadingOverlayPro`, it basically has the same constructors as `LoadingOverlay` and you do not need any additional configurations like the other packages.

```
LoadingOverlayPro({
    Key key,
    @required this.isLoading,
    @required this.child,
    this.colorBackground = Colors.black54,
    this.progressIndicator = const LoadingBouncingLine.circle(),
  });

// only isLoading && child is required
```

goodluck, and goodspeed👍

**Comment by java-james** [comment]
Thanks for the PR I will get in to reviewing this.

**Comment by java-james** [comment]
This should be addressed in https://github.com/java-james/loading_overlay/commit/76cccfbe9a1d9370e99f90dc9267e7a8b057332f

Thanks for raising

**Pull request closed without merging**
